package org.hibernate.dto;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

@Entity
@Table(name = "EMP_DETAILS")
public class EmpDetails {

	/**
	 * Below is the surrogate key whose values are generated by hibernate
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="EMP_ID")
	private int empId;

	/**
	 * This means create the property as it is by using its default
	 * hibernate-sql compatibility
	 */
	@Basic
	@Column(name="EMP_NAME")
	private String name;

	/**
	 * Stores only the date and ignores the timestamp
	 */
	@Temporal(TemporalType.DATE)
	@Column(name="EMP_DOB")
	private Date dob;

	
	/**
	 * Override default column names set in homeAddress
	 */
	@Embedded
	@AttributeOverrides({
	@AttributeOverride(name="street", column=@Column(name="HOME_STREET_NAME")),
	@AttributeOverride(name="town", column=@Column(name="HOME_TOWN_NAME"))
		})
	private Address homeAddress;
	
	@Embedded
	private Address officeAddress;

	/**
	 * Mark as transient when you do not want hibernate to store this field in
	 * db
	 */
	@Transient
	@Column(name="EMP_HOBBY")
	private String hobby;

	public String getHobby() {
		return hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public int getEmpId() {
		return empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Address getHomeAddress() {
		return homeAddress;
	}

	public void setHomeAddress(Address homeAddress) {
		this.homeAddress = homeAddress;
	}

	public Address getOfficeAddress() {
		return officeAddress;
	}

	public void setOfficeAddress(Address officeAddress) {
		this.officeAddress = officeAddress;
	}

}
